var reason_code_dict = {
    'Account Opening Docs Exceptions (Withdarawal & Trades Disallowed)': {'codes': '2,5,6,7,8,10',
    'reason_split': ['BLOCKED REASON: ACCOUNT OPENING',
    'DOCS EXCEPTIONS (WITHDARAWAL &',
    'TRADES DISALLOWED)'],
    'reason_split_len': 3,
    'codes_split': ['2', '5', '6', '7', '8', '10'],
    'codes_split_len': 6},
    'Account Opening Docs Exceptions (Withdrawal Disallowed': {'codes': '2,10',
    'reason_split': ['BLOCKED REASON: ACCOUNT OPENING',
    'DOCS EXCEPTIONS (WITHDRAWAL',
    'DISALLOWED'],
    'reason_split_len': 3,
    'codes_split': ['2', '10'],
    'codes_split_len': 2},
    'Account Opening Docs Exceptions (Trades Disallowed)': {'codes': '5,6,7,8',
    'reason_split': ['BLOCKED REASON: ACCOUNT OPENING',
    'DOCS EXCEPTIONS (TRADES DISALLOWED)'],
    'reason_split_len': 2,
    'codes_split': ['5', '6', '7', '8'],
    'codes_split_len': 4},
    'Account Opening Docs Exceptions (Long Exceptions)': {'codes': '81',
    'reason_split': ['BLOCKED REASON: ACCOUNT OPENING',
    'DOCS EXCEPTIONS (LONG EXCEPTIONS)'],
    'reason_split_len': 2,
    'codes_split': ['81'],
    'codes_split_len': 1},
    'Deceased/Estate Account': {'codes': '81',
    'reason_split': ['BLOCKED REASON: DECEASED/ESTATE', 'ACCOUNT'],
    'reason_split_len': 2,
    'codes_split': ['81'],
    'codes_split_len': 1},
    'Missing Mandatory Documents > 3 months for Periodic Review': {'codes': '2,10',
    'reason_split': ['BLOCKED REASON: MISSING MANDATORY',
    'DOCUMENTS > 3 MONTHS FOR PERIODIC',
    'REVIEW'],
    'reason_split_len': 3,
    'codes_split': ['2', '10'],
    'codes_split_len': 2},
    'Pending Documents > 6 months for Periodic Review': {'codes': '2,10',
    'reason_split': ['BLOCKED REASON: PENDING DOCUMENTS >',
    '6 MONTHS FOR PERIODIC REVIEW'],
    'reason_split_len': 2,
    'codes_split': ['2', '10'],
    'codes_split_len': 2},
    'HK CIES Account': {'codes': '2,7,10',
    'reason_split': ['BLOCKED REASON: HK CIES ACCOUNT'],
    'reason_split_len': 1,
    'codes_split': ['2', '7', '10'],
    'codes_split_len': 3},
    'Pending Documents > exBW Remediation Review Due date (1st week of May 2018)': {'codes': '2,10',
    'reason_split': ['BLOCKED REASON: PENDING DOCUMENTS >',
    'EXBW REMEDIATION REVIEW DUE DATE',
    '(1ST WEEK OF MAY 2018)'],
    'reason_split_len': 3,
    'codes_split': ['2', '10'],
    'codes_split_len': 2},
    'Uncollected Holdmail/ Returned Mail': {'codes': '81',
    'reason_split': ['BLOCKED REASON: UNCOLLECTED', 'HOLDMAIL/ RETURNED MAIL'],
    'reason_split_len': 2,
    'codes_split': ['81'],
    'codes_split_len': 1},
    'Non-AI status': {'codes': '5,6,7,9',
    'reason_split': ['BLOCKED REASON: NON-AI STATUS'],
    'reason_split_len': 1,
    'codes_split': ['5', '6', '7', '9'],
    'codes_split_len': 4},
    'Non-AI status (DPM Accoutns)': {'codes': '5,6,7,9',
    'reason_split': ['BLOCKED REASON: NON-AI STATUS (DPM', 'ACCOUTNS)'],
    'reason_split_len': 2,
    'codes_split': ['5', '6', '7', '9'],
    'codes_split_len': 4},
    'Dormant Accounts': {'codes': '81',
    'reason_split': ['BLOCKED REASON: DORMANT ACCOUNTS'],
    'reason_split_len': 1,
    'codes_split': ['81'],
    'codes_split_len': 1},
    'Missing Mandatory Docs': {'codes': '81',
    'reason_split': ['BLOCKED REASON: MISSING MANDATORY', 'DOCS'],
    'reason_split_len': 2,
    'codes_split': ['81'],
    'codes_split_len': 1},
    'Special Monitoring by On-boarding Team': {'codes': '81',
    'reason_split': ['BLOCKED REASON: SPECIAL MONITORING',
    'BY ON-BOARDING TEAM'],
    'reason_split_len': 2,
    'codes_split': ['81'],
    'codes_split_len': 1},
    'Special Monitoring by Monitoring Team': {'codes': '81',
    'reason_split': ['BLOCKED REASON: SPECIAL MONITORING', 'BY MONITORING TEAM'],
    'reason_split_len': 2,
    'codes_split': ['81'],
    'codes_split_len': 1},
    'Special Monitoring by AML Advisory Team': {'codes': '81',
    'reason_split': ['BLOCKED REASON: SPECIAL MONITORING',
    'BY AML ADVISORY TEAM'],
    'reason_split_len': 2,
    'codes_split': ['81'],
    'codes_split_len': 1},
    'Special Monitoring by Client Review Team': {'codes': '81',
    'reason_split': ['BLOCKED REASON: SPECIAL MONITORING',
    'BY CLIENT REVIEW TEAM'],
    'reason_split_len': 2,
    'codes_split': ['81'],
    'codes_split_len': 1},
    'US Person (Onshore)': {'codes': '4,5,6,7,8,9,10',
    'reason_split': ['BLOCKED REASON: US PERSON (ONSHORE)'],
    'reason_split_len': 1,
    'codes_split': ['4', '5', '6', '7', '8', '9', '10'],
    'codes_split_len': 7},
    'US Person (Offshore)': {'codes': '5,6,7,8,9,10',
    'reason_split': ['BLOCKED REASON: US PERSON', '(OFFSHORE)'],
    'reason_split_len': 2,
    'codes_split': ['5', '6', '7', '8', '9', '10'],
    'codes_split_len': 6},
    'Ring Fenced Accounts': {'codes': '1,2,3,4,5,6,7,9,10',
    'reason_split': ['BLOCKED REASON: RING FENCED', 'ACCOUNTS'],
    'reason_split_len': 2,
    'codes_split': ['1', '2', '3', '4', '5', '6', '7', '9', '10'],
    'codes_split_len': 9},
    'Deferred W8/ W8 Ben not submitted/ W8 Waived': {'codes': '81',
    'reason_split': ['BLOCKED REASON: DEFERRED W8/ W8 BEN',
    'NOT SUBMITTED/ W8 WAIVED'],
    'reason_split_len': 2,
    'codes_split': ['81'],
    'codes_split_len': 1},
    'Expired ID (Passport & ID Card)': {'codes': '81',
    'reason_split': ['BLOCKED REASON: EXPIRED ID', '(PASSPORT & ID CARD)'],
    'reason_split_len': 2,
    'codes_split': ['81'],
    'codes_split_len': 1},
    'AAR Overdue': {'codes': '81',
    'reason_split': ['BLOCKED REASON: AAR OVERDUE'],
    'reason_split_len': 1,
    'codes_split': ['81'],
    'codes_split_len': 1},
    'Triggered Event': {'codes': '81',
    'reason_split': ['BLOCKED REASON: TRIGGERED EVENT'],
    'reason_split_len': 1,
    'codes_split': ['81'],
    'codes_split_len': 1},
    'MAS626 - Director ID': {'codes': '81',
    'reason_split': ['BLOCKED REASON: MAS626 - DIRECTOR', 'ID'],
    'reason_split_len': 2,
    'codes_split': ['81'],
    'codes_split_len': 1},
    'VC Assessment': {'codes': '81',
    'reason_split': ['BLOCKED REASON: VC ASSESSMENT'],
    'reason_split_len': 1,
    'codes_split': ['81'],
    'codes_split_len': 1},
    'FIN Crime': {'codes': '81',
    'reason_split': ['BLOCKED REASON: FIN CRIME'],
    'reason_split_len': 1,
    'codes_split': ['81'],
    'codes_split_len': 1},
    'Client Non-Contactable': {'codes': '81',
    'reason_split': ['BLOCKED REASON: CLIENT NON-', 'CONTACTABLE'],
    'reason_split_len': 2,
    'codes_split': ['81'],
    'codes_split_len': 1},
    'Account blocked for Increased Monitoring Purposes': {'codes': '81',
    'reason_split': ['BLOCKED REASON: ACCOUNT BLOCKED FOR',
    'INCREASED MONITORING PURPOSES'],
    'reason_split_len': 2,
    'codes_split': ['81'],
    'codes_split_len': 1},
    'Pending Direct Marketing Consent': {'codes': '81',
    'reason_split': ['BLOCKED REASON: PENDING DIRECT', 'MARKETING CONSENT'],
    'reason_split_len': 2,
    'codes_split': ['81'],
    'codes_split_len': 1},
    'Special Monitoring by Front Office Team': {'codes': '6,7',
    'reason_split': ['BLOCKED REASON: SPECIAL MONITORING',
    'BY FRONT OFFICE TEAM'],
    'reason_split_len': 2,
    'codes_split': ['6', '7'],
    'codes_split_len': 2},
    'Business Exit': {'codes': '81',
    'reason_split': ['BLOCKED REASON: BUSINESS EXIT'],
    'reason_split_len': 1,
    'codes_split': ['81'],
    'codes_split_len': 1},
    'Credit Condition': {'codes': '81',
    'reason_split': ['BLOCKED REASON: CREDIT CONDITION'],
    'reason_split_len': 1,
    'codes_split': ['81'],
    'codes_split_len': 1},
    'Redemption of Insurance and Mortgages': {'codes': '1',
    'reason_split': ['BLOCKED REASON: REDEMPTION OF', 'INSURANCE AND MORTGAGES'],
    'reason_split_len': 2,
    'codes_split': ['1'],
    'codes_split_len': 1},
    'Litigation / Client Dispute / Injunction Order': {'codes': '81',
    'reason_split': ['BLOCKED REASON: LITIGATION / CLIENT',
    'DISPUTE / INJUNCTION ORDER'],
    'reason_split_len': 2,
    'codes_split': ['81'],
    'codes_split_len': 1},
    'Special Monitoring by Legal': {'codes': '81',
    'reason_split': ['BLOCKED REASON: SPECIAL MONITORING', 'BY LEGAL'],
    'reason_split_len': 2,
    'codes_split': ['81'],
    'codes_split_len': 1},
    'Special Monitoring by Legal - Minor Account': {'codes': '4,6,7,9',
    'reason_split': ['BLOCKED REASON: SPECIAL MONITORING',
    'BY LEGAL - MINOR ACCOUNT'],
    'reason_split_len': 2,
    'codes_split': ['4', '6', '7', '9'],
    'codes_split_len': 4},
    'Special Monitoring by BRM': {'codes': '81',
    'reason_split': ['BLOCKED REASON: SPECIAL MONITORING', 'BY BRM'],
    'reason_split_len': 2,
    'codes_split': ['81'],
    'codes_split_len': 1},
    'Marketing Guidelines Restriction': {'codes': '81',
    'reason_split': ['BLOCKED REASON: MARKETING', 'GUIDELINES RESTRICTION'],
    'reason_split_len': 2,
    'codes_split': ['81'],
    'codes_split_len': 1},
    'Defer SR': {'codes': '5,6,7,8,9',
    'reason_split': ['BLOCKED REASON: DEFER SR'],
    'reason_split_len': 1,
    'codes_split': ['5', '6', '7', '8', '9'],
    'codes_split_len': 5},
    'New NPFFI AC - No securities related transaction allowed': {'codes': '7,8,9,10,12',
    'reason_split': ['BLOCKED REASON: NEW NPFFI AC - NO',
    'SECURITIES RELATED TRANSACTION',
    'ALLOWED'],
    'reason_split_len': 3,
    'codes_split': ['7', '8', '9', '10', '12'],
    'codes_split_len': 5},
    'Undocumented accounts / Accounts with expired W-series forms - No new purchase / transfer in US securities': {'codes': '7,9',
    'reason_split': ['BLOCKED REASON: UNDOCUMENTED',
    'ACCOUNTS / ACCOUNTS WITH EXPIRED',
    'W-SERIES FORMS - NO NEW PURCHASE /',
    'TRANSFER IN US SECURITIES'],
    'reason_split_len': 4,
    'codes_split': ['7', '9'],
    'codes_split_len': 2},
    'Mismatched of Risk Profile': {'codes': '1,9',
    'reason_split': ['BLOCKED REASON: MISMATCHED OF RISK', 'PROFILE'],
    'reason_split_len': 2,
    'codes_split': ['1', '9'],
    'codes_split_len': 2},
    'Holdmail decommissioning': {'codes': '81',
    'reason_split': ['BLOCKED REASON: HOLDMAIL', 'DECOMMISSIONING'],
    'reason_split_len': 2,
    'codes_split': ['81'],
    'codes_split_len': 1},
    'EEA Account': {'codes': '6,7,8',
    'reason_split': ['BLOCKED REASON: EEA ACCOUNT'],
    'reason_split_len': 1,
    'codes_split': ['6', '7', '8'],
    'codes_split_len': 3}
}

var reason = 'Undocumented accounts / Accounts with expired W-series forms - No new purchase / transfer in US securities'

console.log("Click this many times to add posting restricts: "+ reason_code_dict[reason].codes_split_len)
for (let i = 0; i < reason_code_dict[reason].codes_split_len; i++) {
    console.log(reason_code_dict[reason].codes_split[i])
}
console.log("Click this many times to add posting remarks: "+ reason_code_dict[reason].reason_split_len)
for (let i = 0; i < reason_code_dict[reason].reason_split_len; i++) {
    console.log(reason_code_dict[reason].reason_split[i])
}


